---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: server
    run_list:
      - recipe[elk::default]
      - recipe[elk::elasticsearch]
      - recipe[elk::logstash]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      firewall:
        allow_ssh: true
      elastic:
        cluster: 'kitchen-sink'
        data_dir: '/srv/elasticsearch/data'
        log_dir: '/srv/elasticsearch/logs'
