name 'elk'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elk'
long_description 'Installs/Configures elk'
version '0.1.0'
source_url 'https://github.com/cagedata/chef-elk'
issues_url 'https://github.com/cagedata/chef-elk/issues'

depends 'yum', '~> 4.0.0'
depends 'firewall', '~> 2.5.2'
depends 'selinux', '~> 0.9.0'
